sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZLXPjVDdhCCp9klscZFmxeQr2ZCiku6dcMD47NRw4KbI7708hQffn4w1yX4JfJnd7sV9jlewNCZ5MwyjQFSHgl9yTEmc2ZT7WMHuvaZnHSaVV2jLA2O2doiksBXsa5zbdDmpcdsKvXuDf2ja6/7cigabDucByN0MLnVTmEKDvsHrmwTv5WegPYEOk7eCeU5loGpcO4FLe1W9F4UWN7PiJiozccIaojyIjCrRwYUG9DF5AQDqZukoOxNRnXrk9mbPSwZ3YCSwF6ShgpQqciwINBTIcjSqhQQPmO9J0jDJY++5WfBsBkLC9wqI24Ynqxrf/pw3NFR72Xm0SNNXcqbReJuDm81wZTNyD04+ndJigsse/kwIqKr08UNnSIjXK/Xw/+Q3urQWuig/ex4ASAmCmux/HX01es5PTYTTPoeBFX3EACzVpub2+7uLlwKjA0fuL2APVLHve5hdlOMbXS8DPgXh/lh0JkHwZMsr2EVrGUTj7nVQKZrhpDn5Ym4cnoGRYFuQRzCBEH/R3n2SGfBy379tSUYyXpLIWgVkxuREQErBXubrdbb/2+M1L6IRBcuO1LXxLhV569CtYdIxffbsSbpvCNktjmvTRwEX+HQZB3mxIT9paTujqvdZlGdeSdSe7gPHtHD/Xhluc5YZK4ts6h8764TG1l9Rc3t9VpekeOo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Det-Gamle-Testamente-af-1931_2144
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy